### ISSUE TITLE
Corner plots of inferred parameters for some of the systems

### ISSUE THREAD

**Issue by aagnello** [tommasotreu/HIGHRESOLUTIONIMAGING#13]
The code gives gamma-prime, bus also R_eff, q_source etc. The paper would benefit appreciably if we could plot the combined inference on, say: gamma prime, R_eff, q_source; or on other parameters that may have a lot of degeneracy. We wouldn;t need it done on all systems, just one arrangement of instrument and exposure time for each of the four lens configurations. TT and AA think this would be a *very* quick task for @drphilmarshall .

**Comment by drphilmarshall** [comment]
Hi: this is not a quick task for me - I can't see the data file that you want plotted, and there is no documentation on or example of running the code that you want extended. Since I didn't know where to start, I improved the documentation of the code that I think you want to use, to help @XiaoleiMeng make her own plots. Here's the [CornerPlotter repo](https://github.com/drphilmarshall/pappy/blob/master/README.md) - let me know if you need more help!

**Comment by aagnello** [comment]
good call, in fact I don't think all the material is on the repo

**Comment by XiaoleiMeng** [comment]
Hi, guys, I tried upload some materials on the GitHub, they are on HIGHRESOLUTIONIMAGING/docs/results/135949/, named 135949_HST, 135949_JWST and so on. There are 90 .cpkl file (13 M for each cpkl file) for each lens system each telescope. It will costs 2 hours for each lens system each telescope when uploading. Totally 2~3 days for all the materials. So I think it's better that I plot the figure myself using Phil's code. Thanks Phil! If there is any problem I will disturb you with them. Thank you very much guys~
