### ISSUE TITLE
Gaussian and Moffat PSF

### ISSUE THREAD

**Issue by XiaoleiMeng** [tommasotreu/HIGHRESOLUTIONIMAGING#35]
(2)ItismentionedthattheGaussianPSFsareadoptedforEuclid,WFIRST, and LSST. I’m a little bit concerned about this, because PSFs are known to be more extended that Gaussian (particularly for space ob- servations). They are better described by the Moffat profile. Is this difference of the PSF not important? In fact it looks straightforward to repeat the analysis for several different PSF shapes (different β in the Moffat profile for example) to check this effect.
----------------------------------------------------------------------------

The referee suggests to use the Moffat PSF which is more extended than Gaussian for Euclid, WFIRST, and LSST. In particular, the referee hopes us to repeat the analysis for several different PSF shapes (different $\beta$ in the Moffat profile for example) to check our results. 

In our previous work, we use Gaussian PSF, in which the $\sigma$ is defined by $\sigma$ = FWHM/2.35/pixel scale (Gaussian 1). In other's work, the $\sigma$ in Gaussian is equal $\mathrm{FWHM}/2/\sqrt{2\mathrm{ln}(2)}$ (Gaussian 2). The normalized intensity profile of a Gaussian function is given by
\begin{equation}
	\label{eq:psf_gaussian}
	I(r) = \mathrm{exp}\left(\frac{-0.5 r^2}{\sigma^{2}}\right)
\end{equation}

In Moffat case, the intensity profile function is
\begin{equation}
	\label{eq:psf_moffat}
	I(r) = \left(1+\frac{r^2}{\alpha^{2}}\right)^{-\beta}
\end{equation}
in which the parameter $\alpha$ is derived by $\mathrm{FWHM}/2/\sqrt{2^{1/\beta}-1}$. Apparently, in the case of $\beta$ = $\infty$, the Moffat profile results into a Gaussian profile.

In order to show more clearly, I plot the Moffat and Gaussian PSFs for Euclid with $\mathrm{FWHM} = 0.18''$ as an example in Fig. 1.

\begin{figure}
    \includegraphics[width=0.5\textwidth]{psf_gaussian_moffat}
    \caption{Top panel: The normalized intensity profile of two Gaussian PSFs and Moffat PSFs with different values of $\beta$. Middle and bottom panels: The differences between the normalized Gaussian PSFs (Gaussian 1 and 2) and the normalized Moffat PSFs.}
    \label{fig:psf_g_m}
\end{figure}

So, do you think which PSF shapes we should use to repeat our simulations for Euclid, WFIRST, and LSST? $\beta$ are 1.5, 3.0, 4.765 (which is the best fit to the PSF predicted from atmospheric turbulence theory according to Trujillo et al.), and 6.0? Is it necessary to repeat the Gaussian 2 PSF?

Another silly question, the reported FWHM values are the same in Gaussian and Moffat?

Another question, how do we control the pixel scale in Moffat PSF?

![psf_gaussian_moffat](https://cloud.githubusercontent.com/assets/8421271/9086918/25ab2262-3bba-11e5-9c5b-34b39673bcdd.png)

**Comment by XiaoleiMeng** [comment]
Hi, guys, I think this question is the most time-consuming job in this revision. I'm afraid we have to simulated mock systems with Moffat PSF for Euclid, WFIRST, and LSST. What do you think about my proposal and questions mentioned above?

**Comment by drphilmarshall** [comment]
Maybe we can do a small scale test, just for one of the space based
observations? I do not expect our results to change much, because the ring
information is mostly astrometric (its the relative positions of the
brightness fluctuations that matters most) and so will be most sensitive to
the core of the PSF (which is well modeled by a Gaussian). Using a Moffat
(with broad wings), or adding a second, fatter Gaussian should only change
the results by reducing the signal to noise of the sharp features - and
astrometric precision goes down only like the square root of the S/N.

**Comment by tommasotreu** [comment]
Hi Xiao-Lei, I do not understand your comments above. First, the correct expression is sigma=FWHM/2.35 for a gaussian, where 2.35 is the approximation of 2 * sqrt(2) *sqrt(ln(2), as it is trivial to show. Both quantities are in the same units so there should not be a pixel scale in the transformation.

Aside from that, I agree with Phil that it probably won't matter in the end. So  I agree with his suggestion to run moffats as a test. I would do it just for WFIRST, which is the one where we think there is a hope.
So I propose you run simulations of WFIRST images keeping the FWHM fixed at 0.15", then run moffats for beta=1.5,3,4.5, 6.0 and let's see how the results change. Just keep the same exposure time, since it's a survey and let's see how the precision degrades.

**Comment by XiaoleiMeng** [comment]
Very well, totally agree with you. I will run these new simulations right now. I am terribly sorry that I made a mistake of sigma calculation of PSF in previous simulations for Euclid, WFIRST, and LSST. How can we save this situation? explain it to the referee and simulate with right sigma again? Very sorry again for my fault.

**Comment by XiaoleiMeng** [comment]
This is a misunderstanding. I did the right thing before. Now the new results with Moffat PSF with different \beta have been finished. Please see the response to the referee.
